name: Tests

on: [push, pull_request]

env:
  PYTHON_LATEST: 3.9


jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, 3.10-dev]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache dependencies
        id: cache-dependencies
        uses: cache-deps 
        with:
          path: |
            ${{ env.pythonLocation }}/bin/*
            ${{ env.pythonLocation }}/lib/*
            ${{ env.pythonLocation }}/scripts/*
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('setup.py', 'requirements.txt') }}
      - name: Install silicium with all dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          pip install -Ur silicium/requirements_dev.txt
          python silicium/setup.py
      - name: Lint
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == env.PYTHON_LATEST
        run: flake8
      - name: Run Tests
        run: python -m tox --skip-missing-interpreters
